### PR TITLE
Remove trailing space for void elements

### LINKED ISSUE #279: Void elements have whitespace at closing
Preact: ``
React: ``

Not a critical issue but would be nice to match react's render to string output and it avoids having to do further minification.

### PR DESCRIPTION
**Pull request by JoviDeCroock**
Marked as major in case people rely on this for tests

Fixes #279

### CODE REVIEW

**Comment by andrewiggins** [comment]
What's the benefit here? Seems like it could be a really difficult change for people to pick up if lots of tests use this.

**Comment by JoviDeCroock** [comment]
The being more in-line with the output React produces and it being a tad smaller resounded with me, however open to rebuttal there :D

**Review by developit — APPROVED** [review]

**Comment by developit** [comment]
Not sure how this works with Changesets, but could we somehow put this into whatever the next major is, rather than creating a major for this change on its own?

**Comment by JoviDeCroock** [comment]
@developit added it

**Review by andrewiggins — APPROVED** [review]
React compat seems useful. Let's do it in next major

**Pull request merged**
